version: '3.3'

services:
  cvat_ci:
    image: cvat_ci
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile.ci
    depends_on:
      - cvat
      - cvat_ui
      - cvat_proxy
    environment:
      COVERALLS_REPO_TOKEN:
      CONTAINER_COVERAGE_DATA_DIR:
      GITHUB_WORKSPACE:
      GITHUB_RUN_ID:
      GITHUB_HEAD_REF:
      GITHUB_RUN_NUMBER:
    volumes:
      - ${HOST_COVERAGE_DATA_DIR}:${CONTAINER_COVERAGE_DATA_DIR}
