name: Cache
on:
  push:
    branches:
      - 'develop-tmp'

jobs:
  Caching_CVAT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /tmp/cvat_cache
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.2

      - name: Caching CVAT server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          cache-from: type=local,src=/tmp/cvat_cache
          cache-to: type=local,dest=/tmp/cvat_cache-new

      # - name: Caching CVAT ci
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile.ci
      #     cache-from: type=local,src=/tmp/cvat_cache
      #     cache-to: type=local,dest=/tmp/cvat_cache-new
      #     tags: cvat_ci:latest

      # - name: Caching CVAT UI
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile.ui
      #     cache-from: type=local,src=/tmp/cvat_cache
      #     cache-to: type=local,dest=/tmp/cvat_cache-new
      #     tags: openvino/cvat_ui:latest

      - name: Moving cache
        run: |
          docker images
          docker inspect openvino/cvat_server
          rm -rf /tmp/cvat_cache
          mv /tmp/cvat_cache-new /tmp/cvat_cache
