name: Get artifact URL

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'URL to runs'
        required: true

jobs:
  get_artifact_url:
    runs-on: ubuntu-latest
    steps:
      - name: Get link to artifact
        run: |
          tmp_art_url="https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.inputs.run_id }}/artifacts"
          GITHUB_API_REPOS="https://api.github.com/repos"
          URL_RUN_ID="${GITHUB_API_REPOS}/${{ github.repository }}/actions/runs/${{ github.event.inputs.run_id }}"
          URL_ARTIFACTS=$(curl -s -H "Accept: application/vnd.github.v3+json" ${URL_RUN_ID} | jq '.artifacts_url')
          CHECK_SUITE_ID=$(curl -s -H "Accept: application/vnd.github.v3+json" ${URL_RUN_ID} | jq '.check_suite_id')
          ARTIFACT_ID=$(curl -s -H "Accept: application/vnd.github.v3+json" ${URL_ARTIFACTS} | jq '.artifacts[].id')

          echo "URL_RUN_ID = ${URL_RUN_ID}"
          echo "CHECK_SUITE_ID = ${CHECK_SUITE_ID}"
          echo "URL_ARTIFACTS = ${URL_ARTIFACTS}"
          echo "ARTIFACT_ID = ${ARTIFACT_ID}"
          echo "Link to artifact: https://github.com/${{ github.repository }}/suites/${CHECK_SUITE_ID}/artifacts/${ARTIFACT_ID}"
