name: Linters check

on:
  pull_request:
  workflow_dispatch:

jobs:
  linters_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: 12
      - id: files
        uses: jitterbit/get-changed-files@v1

      - name: Install node modules and create a report folder
        run: |
          npm ci
          for folders in `find -maxdepth 1 -name "cvat-*" -type d`; do
            cd $folders && npm ci && cd ..
          done
          mkdir -p linter_reports

      - name: ESlint check
        if: always()
        run: |
          for files in ${{ steps.files.outputs.added_modified }}; do
            extension="${files##*.}"
            if [[ $extension == 'js' || $extension == 'ts' || $extension == 'jsx' || $extension == 'tsx' ]]; then
              changed_files_eslint+=" ${files}"
            fi
          done
          echo "ESlint version: "`npx eslint --version`
          if [[ ! -z ${changed_files_eslint} ]]; then
            echo "The files will be checked: "`echo ${changed_files_eslint}`
            npx eslint ${changed_files_eslint} --output-file ./linter_reports/eslint_check.html --format html
          else
            echo "No files with the \"js|ts|jsx|tsx\" extension found"
          fi

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: linter_check_reports
          path: linter_reports

      - name: Dispatch workflow_dispatch event
        if: always()
        uses: ph-fritsche/action-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          ident: get_artifact_url.yml
          payload: '{"run_id":"${{ github.run_id }}"}'
