# This is a basic workflow to help you get started with Actions

name: CVAT

# Controls when the action will run.
on: [push, pull_request]

env:
  CONTAINER_COVERAGE_DATA_DIR: "/coverage_data"
  HOST_COVERAGE_DATA_DIR: "${GITHUB_WORKSPACE}"
  DJANGO_SU_NAME: "admin"
  DJANGO_SU_EMAIL: "admin@localhost.company"
  DJANGO_SU_PASSWORD: "12qwaszx"
  API_ABOUT_PAGE: "localhost:8080/api/v1/server/about"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
            node-version: 12
            python-version: '3.5'

      # Runs a set of commands using the runners shell
      - name: Build CVAT
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml build
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml run cvat_ci /bin/bash -c 'coverage run -a manage.py test cvat/apps utils/cli && mv .coverage ${CONTAINER_COVERAGE_DATA_DIR}'
          docker-compose -f docker-compose.yml -f docker-compose.ci.yml run cvat_ci /bin/bash -c 'cd cvat-data && npm install && cd ../cvat-core && npm install && npm run test && mv ./reports/coverage/lcov.info ${CONTAINER_COVERAGE_DATA_DIR} && chmod a+rwx ${CONTAINER_COVERAGE_DATA_DIR}/lcov.info'
          docker-compose up -d
          docker exec -it cvat bash -ic "echo \"from django.contrib.auth.models import User; User.objects.create_superuser('${DJANGO_SU_NAME}', '${DJANGO_SU_EMAIL}', '${DJANGO_SU_PASSWORD}')\" | python3 ~/manage.py shell"
